FROM node:22-bookworm-slim AS dependencies

WORKDIR /app

COPY package.json package-lock.json ./

RUN npm ci


FROM node:22-bookworm-slim AS builder

WORKDIR /app

ARG NEXT_PUBLIC_PADDLE_CLIENT_TOKEN
ARG NEXT_PUBLIC_PADDLE_ENV
ARG NEXT_PUBLIC_PADDLE_PERSONALITY_PRICE_ID
ARG NEXT_PUBLIC_PADDLE_CAREER_PRICE_ID
ARG NEXT_PUBLIC_PADDLE_ZODIAC_PRICE_ID
ARG NEXT_PUBLIC_PADDLE_K68_PRICE_ID
ARG NEXT_PUBLIC_PADDLE_K912_PRICE_ID

ENV NEXT_TELEMETRY_DISABLED=1
ENV NEXT_PUBLIC_PADDLE_CLIENT_TOKEN=${NEXT_PUBLIC_PADDLE_CLIENT_TOKEN}
ENV NEXT_PUBLIC_PADDLE_ENV=${NEXT_PUBLIC_PADDLE_ENV}
ENV NEXT_PUBLIC_PADDLE_PERSONALITY_PRICE_ID=${NEXT_PUBLIC_PADDLE_PERSONALITY_PRICE_ID}
ENV NEXT_PUBLIC_PADDLE_CAREER_PRICE_ID=${NEXT_PUBLIC_PADDLE_CAREER_PRICE_ID}
ENV NEXT_PUBLIC_PADDLE_ZODIAC_PRICE_ID=${NEXT_PUBLIC_PADDLE_ZODIAC_PRICE_ID}
ENV NEXT_PUBLIC_PADDLE_K68_PRICE_ID=${NEXT_PUBLIC_PADDLE_K68_PRICE_ID}
ENV NEXT_PUBLIC_PADDLE_K912_PRICE_ID=${NEXT_PUBLIC_PADDLE_K912_PRICE_ID}

COPY --from=dependencies /app/node_modules ./node_modules
COPY . .

RUN npm run build -- --webpack


FROM node:22-bookworm-slim AS runner

WORKDIR /app

ENV NODE_ENV=production
ENV NEXT_TELEMETRY_DISABLED=1
ENV HOSTNAME=0.0.0.0
ENV PORT=3000

RUN groupadd --system --gid 1001 nodejs \
    && useradd --system --uid 1001 --gid nodejs nextjs

COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static
COPY --from=builder --chown=nextjs:nodejs /app/public ./public

USER nextjs

EXPOSE 3000

CMD ["node", "server.js"]
